# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build:
    docker:
      - image: fedora:32
    resource_class: medium
    working_directory: ~/build
    steps:
      - checkout
      - run: 'sudo dnf -y -v groupinstall "Development Tools"'
      - run: 'sudo dnf install -y cmake clang gcc-c++ wget git pesign grubby'
      - run: 'sudo dnf install -y openssl-devel bc nano patch mosquitto sparse'
      - run: 'sudo dnf install -y llvm bpftool libbpf libbpf-devel'
      - run: 'sudo dnf install -y elfutils-libelf libcap'
      - run: 'sudo dnf install -y ruby uthash-devel inih-devel'
      - run: 'sudo dnf install -y rpm-build redhat-rpm-config'
      - run: 'cd ~/build && git clone https://${GH_TOKEN}@github.com/tfjmp/camflow-bpf.git'
      - run: 'make prepare'
      - run: 'make clean'
      - run: 'make btf_circle'
      - run: 'make kern'
      - run: 'make skel'
      - run: 'make usr'
      - run: 'make rpm'
workflows:
  build_and_deploy:
    jobs:
      - build
