# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build:
    docker:
      - image: kernelci/build-gcc-8_x86:latest
    resource_class: medium
    working_directory: ~/build
    steps:
      - checkout
      - run: 'apt-get update -qq --allow-releaseinfo-change'
      - run: 'apt-get install -y sudo rpm cpio'
      - run: 'apt-get install -y build-essential rsync libtool libncurses5-dev'
      - run: 'apt-get install -y libncursesw5-dev bc pkg-config zsh libelf-dev'
      - run: 'apt-get install -y bison flex'
      - run: 'cd ~/build && git clone https://${GH_TOKEN}@github.com/tfjmp/provbpf-kernel.git'
      - run: 'cd ~/build/provbpf-kernel && make prepare'
      - run: 'cd ~/build/provbpf-kernel && make save_space'
      - run: 'cd ~/build/provbpf-kernel && make config_circle'
      - run: 'cd ~/build/provbpf-kernel && make build_kernel'
      - run: 'cd ~/build/provbpf-kernel && make install_header'
      - run: 'cd ~/build/provbpf-kernel && make install_kernel'
      - run: 'cd ~/build/provbpf-kernel && make build_bpf'
      - run: 'cd ~/build/provbpf-kernel && make install_bpf'
      - run: 'make prepare_build'
      - run: 'make clean'
      - run: 'make btf_circle'
      - run: 'make kern'
      - run: 'make skel'
      - run: 'make usr'
      - run: 'make rpm'
workflows:
  build_and_deploy:
    jobs:
      - build
